// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(TestAPIContext))]
    partial class TestAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("DataAccess.Models.Actuals", b =>
                {
                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualHouseholds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualPopulation")
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("DataAccess.Models.Estimates", b =>
                {
                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Districts")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatesHouseholds")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatesPopulation")
                        .HasColumnType("TEXT");

                    b.HasKey("State", "Districts");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
